### PR TITLE
Fix #13, Remove .DS_Store file, add this file to .gitignore.

### LINKED ISSUE #13: Remove .DS_Store file
MacOS leftover file that snuck into the repository.

### PR DESCRIPTION
**Pull request by zacnyjegomosc**
**Describe the contribution**
Fixes #13.

**Testing performed**
Steps taken to test the contribution:
- Run bash command: `find . -name ".DS_Store"`

**Expected behavior changes**
- No impact to behavior

**System(s) tested on**
 - Hardware: MacBook Pro
 - OS: macOS 
 - Versions: Catalina (10.15.3)

**Additional context**
N/A

**Third party code**
N/A

**Contributor Info - All information REQUIRED for consideration of pull request**
Marek Glijer
Personal

  - **HAND SIGNED** Individual CLA must be on file (once per release): [Individual CLA](https://github.com/nasa/cFE/blob/master/docs/GSC_18128_Ind_CLA_form_1219.pdf)

*edit* - By @skliper, fixed issue fixed statement to autolink

### CODE REVIEW

**Comment by skliper** [comment]
Thanks @zacnyjegomosc, if you can give me a heads up when you email the CLA I'll keep an eye out for it.

**Comment by zacnyjegomosc** [comment]
> Thanks @zacnyjegomosc, if you can give me a heads up when you email the CLA I'll keep an eye out for it.

@skliper Roger that, all clear.

**Comment by skliper** [comment]
CCB 20200415 - APPROVED

**Comment by zacnyjegomosc** [comment]
> Thanks @zacnyjegomosc, if you can give me a heads up when you email the CLA I'll keep an eye out for it.

It's done @skliper . I've sent my hand-signed CLA via e-mail, a minute ago (to: gsfc-softwarerelease@mail.nasa.gov).

**Comment by skliper** [comment]
Confirmed CLA receipt.

**Pull request merged**
