### PR TITLE
fix #172, updating executable name and version in setup.py

### LINKED ISSUE #172: Update executable name and version in setup.py
The info in setup.py needs to be edited. 

>Rename to "cFS-GroundSystem" and update version to use the number in version.py

_Originally posted by @astrogeco in https://github.com/nasa/cFS-GroundSystem/pull/137#discussion_r598736996_

### PR DESCRIPTION
**Pull request by zachar1a**
**Describe the contribution**
A clear and concise description of what the contribution is.
-Changing executable command from 'startg' to 'cFS-GroundSystem'
-Changing version to be the version stated in version.py

**Testing performed**
Steps taken to test the contribution:
made sure new executable command works 

**Expected behavior changes**
Changing executable command from 'startg' to 'cFS-GroundSystem'

**System(s) tested on**
 - Hardware: MacBook Pro 
 - OS: macOS Big Sur
 - Versions: 11.2.3

**Contributor Info - All information REQUIRED for consideration of pull request**
Zachary Gonzalez - Personal

### CODE REVIEW

**Comment by astrogeco** [comment]
Thanks for the PR!

**Comment by astrogeco** [comment]
@zachar1a can you isolate the commit for each fix in it's own PR? You can use `git rebase -i` or [several other methods](https://github.com/nasa/cFS/blob/d15f7bffc1422e679f9d46c43a896ed85f85fac1/CONTRIBUTING.md#once-a-pull-request-ready-for-review)

Also edit the commit message to follow the standard format You `git commit --amend`
```
Fix #{ISSUE_NUMBER}, Short Description

[Optional] Long Description
```

Thanks for contributing and for being patient as we iron out the kinks in our contribution flows!

**Comment by zachar1a** [comment]
@astrogeco I had made a separate branch for each pr. Should I just do one fix at a time?

**Comment by zanzaben** [comment]
When I run the install command I am getting this error.

/cFS$ pip3 install -e tools/cFS-GroundSystem
Obtaining file:///home/alex/cFS/tools/cFS-GroundSystem
WARNING: No metadata found in ./tools/cFS-GroundSystem
ERROR: Exception:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
status = self.run(options, args)
File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
resolver.resolve(requirement_set)
File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
discovered_reqs.extend(self._resolve_one(requirement_set, req))
File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
abstract_dist = self._get_abstract_dist_for(req_to_install)
File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 265, in _get_abstract_dist_for
return self.preparer.prepare_editable_requirement(req)
File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 554, in prepare_editable_requirement
abstract_dist = _get_prepared_distribution(
File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
abstract_dist.prepare_distribution_metadata(finder, build_isolation)
File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
self.req.prepare_metadata()
File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 568, in prepare_metadata
self._set_requirement()
File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 386, in _set_requirement
if isinstance(parse_version(self.metadata["Version"]), Version):
File "/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl/packaging/version.py", line 56, in parse
return Version(version)
File "/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl/packaging/version.py", line 275, in init
match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by zachar1a** [comment]
Can you still run the tool with python3 /cFS-GroundSystem.py

**Comment by zanzaben** [comment]
yes, python3 GroundSystem.py still works for me.

**Comment by zachar1a** [comment]
Is it possible for you to delete the GroundSystem dir and then reinstall it

**Comment by zanzaben** [comment]
That fixed it.

**Review by zanzaben — APPROVED** [review]

**Comment by astrogeco** [comment]
As for the commits and branches. Typically we do one branch per fix and PR so this one is good. The only thing I would change is the capitalization on the "fix" in the message. I'll comment on the other one as well

**Comment by zachar1a** [comment]
Ok I'll be sure to double check it for next time.

**Pull request merged**
