### PR TITLE
Modified TLM for SB & TBL

### PR DESCRIPTION
**Pull request by evanfitzgerald**
**Describe the contribution**
A clear and concise description of what the contribution is.
- Corrected values so SB and TBL tlm pages load when selected to open. (removing buffer error)

**Testing performed**
Steps taken to test the contribution:
Ran the ground system:
make (in cmdUtil)
python3 GroundSystem.py
Started Telemetry (with Tlm enabled)
Opened Tlm for TBL and SB

**Expected behavior changes**
Now SB and TBL tlm pages open

**System(s) tested on**
Tested on a Raspberry Pi

**Additional context**

**Third party code**

**Contributor Info - All information REQUIRED for consideration of pull request**
Evan Fitzgerald (Personal)

### CODE REVIEW

**Comment by astrogeco** [comment]
Thanks for the contribution! We'll review it in the next week or so.

**Comment by astrogeco** [comment]
Hi @evanfitzgerald thank you for your contribution! Could you sign and email the appropriate Contributor License agreement?

- Corporate: https://github.com/nasa/cFE/blob/main/docs/GSC_18128_Corp_CLA_form_1219.pdf
- Individual: https://github.com/nasa/cFE/blob/main/docs/GSC_18128_Ind_CLA_form_1219.pdf

email it to: `GSFC-SoftwareRelease@mail.nasa.gov` and copy `cfs-program@lists.nasa.gov`


Thanks

**Comment by evanfitzgerald** [comment]
@astrogeco No problem, I will send it now! :)

**Comment by astrogeco** [comment]
> @astrogeco No problem, I will send it now! :)

Got it1

**Comment by skliper** [comment]
@zanzaben or @evanfitzgerald - could you open an issue (detail steps to recreate bug) and link it?

@evanfitzgerald - Once the issue is open, could you update your commit messages to the following pattern:

```
Fix #XXX - Short description

Long description (optional)
```

**Comment by skliper** [comment]
Marking as ignore until the steps above are completed (remove CCB:Ignore and add CCB:Ready once complete).

**Comment by evanfitzgerald** [comment]
@zanzaben @skliper - I opened the issue https://github.com/nasa/cFS-GroundSystem/issues/165. I "redid" the pull request by reforking the repo and making my changes again and naming the commit properly as I had issues with renaming my multiple pushed commits.

**Comment by evanfitzgerald** [comment]
@skliper @zanzaben I additionally redid the pull request as I wasn't sure if this one was still applicable. Please delete it (https://github.com/nasa/cFS-GroundSystem/pull/166) if it is not needed.

**Comment by skliper** [comment]
Duplicate of #166

**Pull request closed without merging**
