### PR TITLE
Resolves #103 Custom header mechanism

### LINKED ISSUE #61: cFS ground system GUI Python code should generate cmd UDP directly
**Is your feature request related to a problem? Please describe.**
Currently the ground system code calls cmdUtil to send commands to the "spacecraft" via UDP messages to CI. This is clunky (and a giant security issue, not that we're that concerned about that...) and Python's quite capable of generating CCSDS UDP packets directly, skipping the need to call cmdUtil.

**Describe the solution you'd like**
I suggest implementing a library function to send commands, and that library function can directly generate CCSDS command UDP traffic. cmdUtil could even be re-written to be a Python program that just wraps that library function rather than requiring a compiler to build an executable version of cmdUtil.

**Describe alternatives you've considered**
Could just stick with current architecture. Currently this requires compiling cmdUtil and ensuring you're in the right location relative to cmdUtil for it to be called. Current calls assume the executable is in "../cmdUtil/cmdUtil" (so, wherever you start the GUI, it assumes cmdUtil is in a subdirectory called "cmdUtil" under the parent directory.

**Additional context**
Add any other context about the feature request here.

**Requester Info**
Christopher.D.Knight@nasa.gov

### LINKED ISSUE #103: Provide mechanism to use different header definitions, same payload definition
**Is your feature request related to a problem? Please describe.**
Multiple header formats are not easily supported in current implementation of the GUI.

**Describe the solution you'd like**
Make it easier (for example cFS version 1 or version 2 selection should be easy).

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by lbleier-GSFC**
**Describe the contribution**
Fixes #103, implemented the ability to allow users to select the header version byte offset, or custom offsets. In order to support this, some relatively major changes had to be implemented:

- A Python-native "mini" `cmdUtil` to send UDP data. The GroundSystem app in its current form is no longer dependent on the external C `cmdUtil` app (also fixes #61, at least partially)
- Using Python's `mmap` module to share data between processes

**Testing performed**
Steps taken to test the contribution:
1. Make changes to code
2. Run program to verify functionality

**Expected behavior changes**
The update allows users to change the byte offsets for sending commands and parsing telemetry, to support different header versions or other implementations of cFS

**Additional context**
- Note that the "mini" `cmdUtil` is only a subset of `cmdUtil`'s full functionality. Should the GroundSystem app be updated in the future, the full `cmdUtil` might need to be used again, or the "mini" `cmdUtil` updated accordingly
- There is a larger issue regarding the GroundSystem app as a whole and interprocess communication (IPC). There are multiple techniques to achieve this, but which technique is preferred, and whether or not GroundSystem should be completely redesigned to avoid IPC in the first place, is a discussion for the CCB.

**Contributor Info - All information REQUIRED for consideration of pull request**
Leor Bleier, NASA GSFC\Code 582

### CODE REVIEW

**Comment by skliper** [comment]
This PR has commits that are already in master.  Can it be cleaned up such that we can review the actual change being proposed here?

**Comment by astrogeco** [comment]
> This PR has commits that are already in master. Can it be cleaned up such that we can review the actual change being proposed here?

I think it's addressed now. Which commits did you notice were "duplicates"?

**Comment by lbleier-GSFC** [comment]
I did do some cleanup, but found a few last-minute issues that I pushed. I can squash those further if necessary

**Comment by astrogeco** [comment]
CCB 2020-07-01: APPROVED

Replace "enhancement" with a valid linking word: [Linking a pull request to an issue](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

Open issue for cross-platform `tmp` location.

Open issue for ZMQ idea

**Comment by astrogeco** [comment]
@lbleier-GSFC if you still have time, can you take a look at the conflicts? If not, maybe @dmknutsen or @JandlynBentley-at-NASA can try

**Comment by lbleier-GSFC** [comment]
> @lbleier-GSFC if you still have time, can you take a look at the conflicts? If not, maybe @dmknutsen or @JandlynBentley-at-NASA can try

Should be good now

**Pull request merged**
