### PR TITLE
Fix #202, naming error

### LINKED ISSUE #202: Telemetry GUI error - Individual telemetry pages do not open due to name errors in GenericTelemetry.py
**Describe the bug**
The Telemetry subsystem windows do not open anymore. When opening a telemetry window such as ES Housekeeping telemetry, it produces an error an error. 

**To Reproduce**
1. Start GroundSystem.py
2. In the cFS Ground System Main Window, hit the "Start Telemetry System" button.
3. In the Telemetry System Page Window, hit the "Display Page" button next to ES HK Tlm

In the console you will see:
NameError: name 'tlm_item_desc' is not defined.

I think the name convention change left a few old names in the file. From tlmItemDesc --> tlm_item_desc. See the Code snips section for all of the errors I found.

**Expected behavior**
Telemetry window should open, displaying packet values in the window.

**Code snips**
Look in cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py:

Line 71: tlmItemSize should be tlm_item_size
Line 79: tlmItemEnum should be tlm_item_enum
Line 82: tlmItemDesc  should be tlm_item_desc
Line 90: gtSignalTlmDatagram should be gt_signal_tlm_datagram

Line 220: tlmItemDesc should be tlm_item_desc
Line 221: tlmItemSize should be tlm_item_size
Line 222: tlmItemFormat should be tlm_item_format

**System observed on:**
 - Hardware - Desktop PC
 - OS: Ubuntu 20.04
 - Versions: Using cFS main branch and associated submodules (1/15/2022)

**Additional context**
N/A

**Reporter Info**
Alan Cudmore NASA/GSFC

### PR DESCRIPTION
**Pull request by paulober**
Sorry for that. Missed that one in conversion...

**Describe the contribution**
- Fixes #202

**Contributor Info - All information REQUIRED for consideration of pull request**
Personal

### CODE REVIEW

**Comment by skliper** [comment]
On Ubuntu20.04 I still get:
```
Traceback (most recent call last):
  File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 253, in <module>
    telem.init_gt_tlm_receiver(subscription)
  File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 88, in init_gt_tlm_receiver
    self.thread.gtSignalTlmDatagram.connect(self.process_pending_datagrams)
AttributeError: 'GTTlmReceiver' object has no attribute 'gtSignalTlmDatagram'
```

**Comment by paulober** [comment]
> On Ubuntu20.04 I still get:
> 
> ```
> Traceback (most recent call last):
>   File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 253, in <module>
>     telem.init_gt_tlm_receiver(subscription)
>   File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 88, in init_gt_tlm_receiver
>     self.thread.gtSignalTlmDatagram.connect(self.process_pending_datagrams)
> AttributeError: 'GTTlmReceiver' object has no attribute 'gtSignalTlmDatagram'
> ```

Should be fixed now.

**Comment by skliper** [comment]
I still get the following errors (and the window doesn't open) when trying to open the ES HK Tlm page.  Maybe I have a more fundamental issue?
```
Generic Telemetry Page started. Subscribed to GroundSystem.0x800
qt.qpa.xcb: X server does not support XInput 2
failed to get the current screen resources
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-jhageman'
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 164, resource id: 90, major code: 130 (Unknown), minor code: 47
qt.qpa.xcb: QXcbConnection: XCB error: 170 (Unknown), sequence: 177, resource id: 90, major code: 146 (Unknown), minor code: 20
Traceback (most recent call last):
  File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 110, in process_pending_datagrams
    self.display_telemetry_item(datagram, k, item_label, item_value)
  File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 77, in display_telemetry_item
    value_field.setText(tlm_item_enum[tlm_index][int(tlm_field[0])])
IndexError: list index out of range
```

**Comment by paulober** [comment]
> I still get the following errors (and the window doesn't open) when trying to open the ES HK Tlm page. Maybe I have a more fundamental issue?
> [...]
> ```python
> Traceback (most recent call last):
>   File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 110, in process_pending_datagrams
>     self.display_telemetry_item(datagram, k, item_label, item_value)
>   File "/home/jhageman/cFS/cFS-GitHub/tools/cFS-GroundSystem/Subsystems/tlmGUI/GenericTelemetry.py", line 77, in display_telemetry_item
>     value_field.setText(tlm_item_enum[tlm_index][int(tlm_field[0])])
> IndexError: list index out of range
> ```

🤔 strange, I just tested it on a new VM and it opens the window without any warnings or errors.

**Comment by skliper** [comment]
I'll  try to take a closer look at it... just did a quick initial check.

**Comment by thnkslprpt** [comment]
> 🤔 strange, I just tested it on a new VM and it opens the window without any warnings or errors.

Working for me now as well, after implementing your bug-fixes to GenericTelemetry.py on my local copy

**Comment by skliper** [comment]
OK, looks like this does fix #217.  I was able to open both TBL and TIME HK pages.  There's still an error with opening ES, I suspect the packet description is out of date.  I'll open a new issue for that, but this change should be able to move forward.

**Comment by chillfig** [comment]
Approved. Just needs confirmation on contributor license agreement (cla). @paulober would you please confirm that you emailed in a cla?

**Comment by paulober** [comment]
> Approved. Just needs confirmation on contributor license agreement (cla). @paulober would you please confirm that you emailed in a cla?

Confirm signed it allready.

**Comment by chillfig** [comment]
> @dzbaker @chillfig What's the status on this one? It's currently broken without it...

This pull request looks good to me to merge. @dzbaker is out of office until November 14. Can the merge wait until then?

**Comment by dzbaker** [comment]
> > @dzbaker @chillfig What's the status on this one? It's currently broken without it...
> 
> This pull request looks good to me to merge. @dzbaker is out of office until November 14. Can the merge wait until then?

@skliper @chillfig Merged!

**Pull request merged**
