### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hello,

This PR will fix : 

- 1 typo in `RoutingService.py`
- 2 typos in `Subsystems/cmdGui/CHeaderParser.py`
- 1 typo in `Subsystems/cmdGui/CommandSystem.py`
- 1 typo in `Subsystems/cmdGui/Parameter.py`
- 1 typo in `Subsystems/tlmGUI/GenericTelemetry.py`
- 1 typo in `Subsystems/tlmGUI/TelemetrySystem.py`

Bye! :robot:

### CODE REVIEW

**Comment by skliper** [comment]
Thanks!  Preference is to use the pull request template.  Have you submitted a CLA (needed to accept an external contribution, just hand sign and email)?

See: https://github.com/nasa/cFE/blob/master/docs/GSC_18128_Corp_CLA_form_1219.pdf or https://github.com/nasa/cFE/blob/master/docs/GSC_18128_Ind_CLA_form_1219.pdf

**Comment by pgrimaud** [comment]
Should I send CLA to GSFC-SoftwareRelease@mail.nasa.gov?

**Comment by skliper** [comment]
@pgrimaud Please do!

**Comment by pgrimaud** [comment]
Email sent 👌

**Comment by skliper** [comment]
Confirmed CLA receipt

**Comment by astrogeco** [comment]
CCB 2020-04-29 : APPROVED

**Pull request merged**
