### PR TITLE
Fix #131 - updated CHeaderParser.py to address specific issues

### LINKED ISSUE #131: CHeaderParser.py misbehaves when parameters are included
**Describe the bug**
See log from run attempted with parameters

[02-Error-with-params.txt](https://github.com/nasa/cFS-GroundSystem/files/5158079/02-Error-with-params.txt)

**To Reproduce**
See log

**Expected behavior**
Successfully parse header

**Code snips**
Researching.

**System observed on:**
Unspecified - from community email list.

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by lbleier-GSFC**
**Describe the contribution**
Fixes #131 addressing issues raised by end user

**Testing performed**
No sample input available so no testing performed; will need to be tested

**Expected behavior changes**
Fix the issues raised in #131 

**Contributor Info - All information REQUIRED for consideration of pull request**
Leor Bleier GSFC\Code 582

### CODE REVIEW

**Comment by yammajamma** [comment]
Convert to draft based on [CCB-20200902](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-02-2020) comments.

**Comment by stanislaw** [comment]
@lbleier-GSFC, it seems to work better now: I add the argument to the SAMPLE_APP_CMD_NOP_CC command and it is displayed correctly in the UI.

However, notice two details above:

1) **0 of 0!**

```
Showing structure 0 of 0 below
```

2) **SAMPLE_APP_CMD_NOP2_CC instead of SAMPLE_APP_CMD_NOP_CC**

```
The following commands have been added with parameters:
['SAMPLE_APP_CMD_NOP2_CC']
```

P.S. To be honest, I don't believe you can fix this once and forever until functional tests are introduced. A python test program could be written and it could exercise all of the user inputs automatically and check the inputs (sending stdin and grepping over stdout).

---

Full input:

```
$ python CHeaderParser.py
Using header files found in CHeaderParser-hdr-paths.txt
We need to save the command into to a pickle file in 'CommandFile/'.
Please do not use any spaces/quotes in your filename. Ex: my_app_cmd_file
What would you like the command file to be saved as? Sample

Unused Commands
-----------------------------------------
(Command 1 of 2) SAMPLE_APP_CMD_NOP_CC
(Command 2 of 2) SAMPLE_APP_CMD_NOP2_CC
Do any commands in Sample require parameters? (yes/no): yes
Enter a value from the list above or -1 to exit: 1
This program will now attempt to find the command structure for SAMPLE_APP_CMD_NOP_CC

Showing structure 0 of 0 below
--------------------------------------------
struct Foo {
uint32 arg1;
};
--------------------------------------------
Enter a value from the list above or -1 to exit: 0



Line (0) -> struct Foo {
Line (1) -> uint32 arg1;
Line (2) -> };
Enter the line of the parameter from the above print-out (-1 to stop): 1
dataTypeOrig: uint32
dataTypeNew: --word
paramName: arg1
paramLen:
stringLen:
Added: arg1 with type --word



Line (0) -> struct Foo {
Line (1) -> };
Enter the line of the parameter from the above print-out (-1 to stop): -1
You have chosen to stop adding parameters.

Unused Commands
-----------------------------------------
Command (1 of 1) SAMPLE_APP_CMD_NOP_CC
Enter a value from the list above or -1 to exit: -1
Exiting.
Thank you for using CHeaderParser.
The following commands have been added with parameters:
['SAMPLE_APP_CMD_NOP2_CC']
```

**Comment by stanislaw** [comment]
This is what happens if I select the second command:

```
python CHeaderParser.py
Using header files found in CHeaderParser-hdr-paths.txt
We need to save the command into to a pickle file in 'CommandFile/'.
Please do not use any spaces/quotes in your filename. Ex: my_app_cmd_file
What would you like the command file to be saved as? SAMPLE_APP_CMD

Unused Commands
-----------------------------------------
(Command 1 of 2) SAMPLE_APP_CMD_NOP_CC
(Command 2 of 2) SAMPLE_APP_CMD_NOP2_CC
Do any commands in SAMPLE_APP_CMD require parameters? (yes/no): yes
Enter a value from the list above or -1 to exit: 2
This program will now attempt to find the command structure for SAMPLE_APP_CMD_NOP2_CC

Showing structure 0 of 0 below
--------------------------------------------
struct Foo {
uint32 arg1;
};
--------------------------------------------
Enter a value from the list above or -1 to exit: 0



Line (0) -> struct Foo {
Line (1) -> uint32 arg1;
Line (2) -> };
Enter the line of the parameter from the above print-out (-1 to stop): 1
dataTypeOrig: uint32
dataTypeNew: --word
paramName: arg1
paramLen:
stringLen:
Added: arg1 with type --word



Line (0) -> struct Foo {
Line (1) -> };
Enter the line of the parameter from the above print-out (-1 to stop): -1
You have chosen to stop adding parameters.
Traceback (most recent call last):
  File "CHeaderParser.py", line 491, in <module>
    used_cmdDesc.append(unused_cmdDesc[command_choice])
IndexError: list index out of range
```

**Comment by lbleier-GSFC** [comment]
> @lbleier-GSFC, it seems to work better now: I add the argument to the SAMPLE_APP_CMD_NOP_CC command and it is displayed correctly in the UI.
> 
> However, notice two details below:
> 
> 1. **0 of 0!**
> 
> ```
> Showing structure 0 of 0 below
> ```
> 
> 1. **SAMPLE_APP_CMD_NOP2_CC instead of SAMPLE_APP_CMD_NOP_CC**
> 
> ```
> The following commands have been added with parameters:
> ['SAMPLE_APP_CMD_NOP2_CC']
> ```
> 
> P.S. To be honest, I don't believe you can fix this once and forever until functional tests are introduced. A python test program could be written and it could exercise all of the user inputs automatically and check the inputs (sending stdin and grepping over stdout).
> 
> Full input:
> 
> ```
> $ python CHeaderParser.py
> Using header files found in CHeaderParser-hdr-paths.txt
> We need to save the command into to a pickle file in 'CommandFile/'.
> Please do not use any spaces/quotes in your filename. Ex: my_app_cmd_file
> What would you like the command file to be saved as? Sample
> 
> Unused Commands
> -----------------------------------------
> (Command 1 of 2) SAMPLE_APP_CMD_NOP_CC
> (Command 2 of 2) SAMPLE_APP_CMD_NOP2_CC
> Do any commands in Sample require parameters? (yes/no): yes
> Enter a value from the list above or -1 to exit: 1
> This program will now attempt to find the command structure for SAMPLE_APP_CMD_NOP_CC
> 
> Showing structure 0 of 0 below
> --------------------------------------------
> struct Foo {
> uint32 arg1;
> };
> --------------------------------------------
> Enter a value from the list above or -1 to exit: 0
> 
> 
> 
> Line (0) -> struct Foo {
> Line (1) -> uint32 arg1;
> Line (2) -> };
> Enter the line of the parameter from the above print-out (-1 to stop): 1
> dataTypeOrig: uint32
> dataTypeNew: --word
> paramName: arg1
> paramLen:
> stringLen:
> Added: arg1 with type --word
> 
> 
> 
> Line (0) -> struct Foo {
> Line (1) -> };
> Enter the line of the parameter from the above print-out (-1 to stop): -1
> You have chosen to stop adding parameters.
> 
> Unused Commands
> -----------------------------------------
> Command (1 of 1) SAMPLE_APP_CMD_NOP_CC
> Enter a value from the list above or -1 to exit: -1
> Exiting.
> Thank you for using CHeaderParser.
> The following commands have been added with parameters:
> ['SAMPLE_APP_CMD_NOP2_CC']
> ```

@stanislaw I agree this needs to be thoroughly tested. I am implementing fixes for the above issues at least for you to try

**Comment by lbleier-GSFC** [comment]
Adding @skliper to follow this

**Comment by stanislaw** [comment]
Sorry for the delay with the feedback. I hope to get to testing this tomorrow.

**Comment by stanislaw** [comment]
I am testing this again. Both issues reported in my latest comment seem to have been fixed with the latest commit b44dc44.

I have also noticed this other group of (hopefully) more trivial issues: the tool always raises exceptions when the Enter key is pressed instead of a number here:

```
Enter the line of the parameter from the above print-out (-1 to stop):
Traceback (most recent call last):
  File "CHeaderParser.py", line 384, in <module>
    param_line = int(
ValueError: invalid literal for int() with base 10: ''
```

and here:

```
Enter a value from the list above or -1 to exit:
Traceback (most recent call last):
  File "CHeaderParser.py", line 249, in <module>
    if command_choice == -1:
NameError: name 'command_choice' is not defined
```

Thank you.

**Comment by lbleier-GSFC** [comment]
> I am testing this again. Both issues reported in my latest comment seem to have been fixed with the latest commit [b44dc44](https://github.com/nasa/cFS-GroundSystem/commit/b44dc44f704053a054c1e56015552e0e6e35c6c3).
> 
> I have also noticed this other group of (hopefully) more trivial issues: the tool always raises exceptions when the Enter key is pressed instead of a number here:
> 
> ```
> Enter the line of the parameter from the above print-out (-1 to stop):
> Traceback (most recent call last):
>   File "CHeaderParser.py", line 384, in <module>
>     param_line = int(
> ValueError: invalid literal for int() with base 10: ''
> ```
> 
> and here:
> 
> ```
> Enter a value from the list above or -1 to exit:
> Traceback (most recent call last):
>   File "CHeaderParser.py", line 249, in <module>
>     if command_choice == -1:
> NameError: name 'command_choice' is not defined
> ```
> 
> Thank you.

OK, should be fixed. Look at this personal service you're getting :)

**Comment by astrogeco** [comment]
[CCB 2020-09-09](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-09-2020) APPROVED

**Pull request merged**
