### PR TITLE
Ignore *.pyc and cmdUtil, #1

### LINKED ISSUE #1: gitignore *.pyc files
Originated from jhageman (74 on babelfish)

git should ignore compiled python files to simplify code cm.

### PR DESCRIPTION
**Pull request by skliper**
Fixes #1 

Work done by @skliper , CLA on file

### CODE REVIEW

**Comment by skliper** [comment]
@avan989 could you review this commit?

**Comment by avan989** [comment]
I could review it

**Comment by avan989** [comment]
I reviewed it.

**Comment by avan989** [comment]
I approve it.

**Pull request merged**
