### PR TITLE
Fix #227, Add input so users can specify the parameter description

### LINKED ISSUE #227: Add parameter description
**Is your feature request related to a problem? Please describe.**
The default behavior for the param description was to be considered null. However I found this not to be very user friendly since if you didn't have the source code with the accepted values you couldn't create a valid command to send.

**Describe the solution you'd like**
A way to specify the parameter description. This could be done by adding an input after specifying a parameter in order for the description of the parameter to be saved

**Requester Info**
Hugo Micael Santos Valente / STRAST / UPM

### PR DESCRIPTION
**Pull request by HugoValente11**
**Describe the contribution**
The default behavior for the param description was to be considered null. However I found this not to be very user friendly since if you didn't have the source code with the accepted values you couldn't create a valid command to send.
My solution was to add an input after specifying a parameter in order for the description of the parameter to be saved.
This way when we open GroundSystem and start creating a command to send, we have some guidelines about the acceptable inputs for the arguments

Screenshot of how the GUI has been affected:
https://ibb.co/9TKXB51

**Testing performed**
Steps taken to test the contribution:
1. Parse document with CHeaderParser.py
2. After selecting line for parameter to add, write (or not) a short description of the values that are acceptable

**Expected behavior changes**
 - Behavior Change: now when we open Ground System the column with the description for the params will be filled instead of the default null which makes it more user friendly

**System(s) tested on**
 - OS: Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Hugo Micael Santos Valente / STRAST / UPM

### CODE REVIEW

**Review by ArjunSharda — APPROVED** [review]

**Comment by dzbaker** [comment]
CCB 8 September 2022: Needs an issue.

**Comment by dzbaker** [comment]
> > @HugoValente11 Thank you for your contribution! Would you be able to create an issue for this PR?
> 
> My bad, when I saw self-assigned I thought that you'd create the issue, didn't realize that you were waiting for me to create it to close the pull. Sure created it now #227

Thanks!

**Review by chillfig — CHANGES_REQUESTED** [review]
Hi @HugoValente11 , would you please change the commit message to follow our [cFS contribution convention](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md)?---> Fix #XYZ, SHORT_DESCRIPTION

One way to do this is to use `git commit --amend` (change commit message) and then `git push --force` from your local branch.

The final commit message may look like: "Fix #227, Add input so users can specify the parameter description

**Comment by chillfig** [comment]
All of the checks are marked as passed, however "Error: The log was not found. It may have been deleted based on retention settings." is the error message displayed in the details of each job in the checks.

**Comment by dzbaker** [comment]
CCB 20 October 2022: @dzbaker will attempt to re-run workflows.

**Comment by HugoValente11** [comment]
> Hi @HugoValente11 , would you please change the commit message to follow our [cFS contribution convention](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md)?---> Fix #XYZ, SHORT_DESCRIPTION

Fixed

**Review by chillfig — APPROVED** [review]

**Comment by dzbaker** [comment]
@HugoValente11 Would you be able to rebase this with main?

**Pull request merged**
