### PR TITLE
Fix #98, Refactor individual UI elements to tables

### LINKED ISSUE #98: Refactor individual fields to table
**Is your feature request related to a problem? Please describe.**
The individual fields in the generic telemetry and command windows use dozens of individual UI elements.

**Describe the solution you'd like**
Replace fields with table widget

**Additional context**
A single table widget would make UI easier to use and maintain

**Requester Info**
Leor Bleier, NASA GSFC\Code 582

### PR DESCRIPTION
**Pull request by lbleier-GSFC**
**Describe the contribution**
Implements feature #98. Change all individual UI elements to table widgets. Update backend code accordingly

**Testing performed**
Steps taken to test the contribution:
1. Replace existing UI elements with table widgets
2. Run software to verify functionality

**Expected behavior changes**
None, should still work as before with new table widgets

**Contributor Info - All information REQUIRED for consideration of pull request**
Leor Bleier, NASA GSFC\Code 582

### CODE REVIEW

**Comment by astrogeco** [comment]
@lbleier-GSFC is this ready?

**Comment by lbleier-GSFC** [comment]
> @lbleier-GSFC is this ready?

Yes

**Comment by skliper** [comment]
Commit history isn't review friendly... I suggest cleaning up so it's easier to tell what changes you are requesting.

**Comment by astrogeco** [comment]
CCB 2020-06-17: APPROVED

**Pull request merged**
